### ISSUE TITLE
Display more detailed radar (include colors representing lighter precip) when conditions are favorable for snow/ice/mixed precip

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/weatherCheck#195]
~~"Radar site" means the physical location of the radar site that we have an image from, i.e. "MKX". We only care if the temperature is cold enough that it _might_ snow~~ ~~and we're going to set the threshold (mostly unscientifically) at 40 degrees F. This only needs to be updated once per hour (which is again just a guess)~~

See #205 

~~This is actually a choice made on the client side; if it looks like conditions might include winter precip, just load the /images/radar version (which isn't filtered) instead of /images/processed (which is filtered)~~

So now instead of having "radar" (the incoming, unprocessed radar images) and "processed" (the cleaned up radar images), we're using a single hunk of php that calls imagemagick functions and takes the fainter radar echoes and makes those colors transparent. Therefore, what needs to be done to resolve this issue has changed.

In https://github.com/airmanopus/weatherCheck/blob/master/cgi-bin/radarFilterTest.php:

If winter precip is possible, then ratchet down the amount of filtering that's done so that kind of light precip shows in the radar image.

Notes:
-  We always return a radar image (even if it's a small one in the case of zero precip) for each radar site anyway; all this issue is doing is changing the filtering of colors that correspond to radar echo strength
-  It's possible that some areas with the adjacent states whose radar images are displayed will be filtered much, and others not so much, depending on conditions (example is a cold front passing through a section of the country where it's rain on one side and snow on the other)

in weathercheck.js
in function stateKMLComplete

```javascript
// get the latlonboxes each radar site
      for (var i = 0; i < numRadarSites; i++) {
        radarLink = stateKMLDoc.getElementsByTagName('href')[i].textContent;
        console.log(radarLink,i);
```
- [ ] Depending on how this works, can also possibly play with the 'opacity' value here
```javascript
        north = stateKMLDoc.getElementsByTagName('north')[i].textContent;
        south = stateKMLDoc.getElementsByTagName('south')[i].textContent;
        east = stateKMLDoc.getElementsByTagName('east')[i].textContent;
        west = stateKMLDoc.getElementsByTagName('west')[i].textContent;
        imageBounds = [[south,west], [north,east]];
        try {
          radarLayer = L.imageOverlay(radarLink,imageBounds, {'opacity': '0.500'});
        }
        catch (err) {
          Raven.captureMessage(err);
          console.log('Radar image ' + radarLink + ' is not available.');
        }

        // and add the radar image to the map
        map.addLayer(radarLayer);

        var radarSite = {
          'link': radarLink,        // link to the radar image to display
          'bounds': imageBounds,    // bounds the image covers sw,ne
          'layer': radarLayer       // L.imageOverlay object
        };
```
Note to self: don't eff with the KML files, they don't need to change!

~~An unanswered question: it's fine to look at the current conditions for the point location where the user is standing, and make a decision to pass parameters to the radar processor to say "give me a radar image that includes the particular colors that usually indicate snow". _But that's just for one radar site_. We don't currently know the conditions at any of the other radar sites whose images we load (and up to now haven't cared), but if we only want to show the snow colors for each particular radar site to get the most accurate picture, then we need to have a way to check the current conditions at each radar site.~~

We can get forecast data for all of the sites with one request. _Win_.

Start here:
https://graphical.weather.gov/xml/rest.php
Also see here:
https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXML.htm
and for the DWML, see here:
https://graphical.weather.gov/xml/mdl/XML/Design/MDL_XML_Design.pdf

From https://graphical.weather.gov/xml/mdl/XML/Design/WebServicesUseGuildlines.php:
- It is recommended a client not make more than one request every five seconds;
- The forecast data is updated no more than once an hour: never request for the same location more than once an hour;
- Please request data for only elements (hourly temp, max temp, wind speed, etc) that you need;

_We_ really only care about two things being returned: _snow amount_ and _ice accumulation_. If either of these is non-zero (meaning there's a chance, any chance) then we're in winter mode for that site and we're going to return the low dbz colors that might (or might not) be snow in the radar image we produce (added: for all of the radar images in that state and in adjacent states).

Tasks
- [ ] Add magic to radarFilterTest.php that checks out locally stored forecast data to see if the requested radar site (/?radarSite=FOO) is expected to experience snow or ice
- [ ] Included in this magic is a way to decide that if a radar site (let's say MKX) is marked as having snow/ice forecast, then all other sites in the state must also return images that include snow/ice colors _and_ all other sites in the states adjacent must also return images that include snow/ice colors
- [ ] Write magic spell that goes and gets current forecast snow amount and ice accumulation for the geographic location of each the radar sites and stores it; must run once per hour after :45
- [x] Make a new list of those sites that doesn't include sites that are "unlikely" to ever see snow/ice so we're only asking for forecast data for sites where we expect to see snow/ice (~~maybe???~~ nope, not really saving anything by doing so)
- [x] Follow the above usage requirements; ~~may need to do some time slicing to make sure we're not ever asking for something more than once per hour~~ only need to download forecast ~~one time and~~ once per hour, so can just run via cron

**Comment by airmanopus** [comment]
When it's cold out, a light drizzle of rain/snow/sleet/ice/etc makes a much bigger difference on the ground, but the way we filter radar noise out also filters out this kind of light precipitation. So if it's cold enough that frozen precip can happen, or (and especially) if it's forecast to happen, display the unfiltered radar image so that the light precip shows up on the radar display. (Also add a notification or indicator to the display that frozen precip is possible.) (Also, use the hourly forecast to determine this.)(

**Comment by airmanopus** [comment]
See #205

**Comment by airmanopus** [comment]
See https://github.com/airmanopus/weatherCheck/commit/ad540228575218ba90b7e5347fbb3889a54360a9 and issue #205. Since we are already getting the current weather for the device location, we can pass that to the above and let it decide what colors can remain in the image that's returned based on the current conditions (the rules for which still need to be defined).

**Comment by airmanopus** [comment]
Bumped to major, since it affects the radar images so much. 
For some background, see http://www.srh.noaa.gov/jetstream/doppler/radarfaq.html#everything

**Comment by airmanopus** [comment]
See http://www.srh.noaa.gov/jetstream/doppler/refl.html ; a couple of points to consider.
- "Value of 20 dBZ is typically the point at which light rain begins."; so normal filtering is probably about right
- I've not (ever, at all) taken color blindness into consideration, and before the new radar filter it would have been difficult; but since I'm adding the capability to send parameters to my radar filter to change what colors are filtered _out_, it's probably a lot more possible to also set up a way to request a radar image that's colored entirely differently.

**Comment by airmanopus** [comment]
Have added more colors that are _normally_ filtered; tl;dr greens and blues that were being displayed especially at night and when there was no actual precip. On a desktop monitor it's fairly obvious what's noise and what isn't, but on a phone the radar noise makes it look like it's monsooning outside when it really isn't (and we can't have _that_). 

We're no longer filtering #ffffff (white). It would take a 75dbz echo for it to appear (and I've seen it happen), so we don't want to filter that color at all. If you see white pictures in the midst of a radar picture you need to find shelter.

The colors we're going to keep when winter precip might be happening are as follows; these are the blue and light blue colors. Anything other than winter precip (so "normally") these colors get filtered out.

- 15 dbz #0300f4
- 10 dbz #019ff4 
- 5 dbz 04e9e7

**Comment by airmanopus** [comment]
Time to answer the question of "how do we know that a given radar site's image needs to show the colors that indicate (potentially very light) snow and ice?"

Start here:
https://graphical.weather.gov/xml/rest.php
Also see here:
https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXML.htm

From https://graphical.weather.gov/xml/mdl/XML/Design/WebServicesUseGuildlines.php:
* It is recommended a client not make more than one request every five seconds;
* The forecast data is updated no more than once an hour: never request for the same location more than once an hour;
* Please request data for only elements (hourly temp, max temp, wind speed, etc) that you need;

We really only care about two things being returned: _snow amount_ and _ice accumulation_. If either of these is non-zero (meaning there's a chance, any chance) then we're in winter mode for that site and we're going to return the low dbz colors that might (or might not) be snow in the radar image we produce.

**Comment by airmanopus** [comment]
This is an example of (I think) the request to make:
https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXMLclient.php?whichClient=NDFDgen&lat=38.99&lon=-77.01&listLatLon=&lat1=&lon1=&lat2=&lon2=&resolutionSub=&listLat1=&listLon1=&listLat2=&listLon2=&resolutionList=&endPoint1Lat=&endPoint1Lon=&endPoint2Lat=&endPoint2Lon=&listEndPoint1Lat=&listEndPoint1Lon=&listEndPoint2Lat=&listEndPoint2Lon=&zipCodeList=&listZipCodeList=&centerPointLat=&centerPointLon=&distanceLat=&distanceLon=&resolutionSquare=&listCenterPointLat=&listCenterPointLon=&listDistanceLat=&listDistanceLon=&listResolutionSquare=&citiesLevel=&listCitiesLevel=&sector=&gmlListLatLon=&featureType=&requestedTime=&startTime=&endTime=&compType=&propertyName=&product=time-series&begin=2004-01-01T00%3A00%3A00&end=2021-10-17T00%3A00%3A00&Unit=e&snow=snow&iceaccum=iceaccum&Submit=Submit

**Comment by airmanopus** [comment]
Can get results for up 200 points at once, which more than covers getting conditions at all of the radar sites on the list with one request.  _Sweet!_

Example:
https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXMLclient.php?whichClient=NDFDgen&listLatLon=43.368091,-88.653475%2041.92799,-88.746946&product=time-series&begin=2017-10-17T19%3A00%3A00&end=2017-10-18T19%3A00%3A00&Unit=e&snow=snow&iceaccum=iceaccum

curl as user agent
```xml
<?xml version="1.0"?>
<dwml version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd">
  <head>
    <product srsName="WGS 1984" concise-name="time-series" operational-mode="official">
      <title>NOAA's National Weather Service Forecast Data</title>
      <field>meteorological</field>
      <category>forecast</category>
      <creation-date refresh-frequency="PT1H">2017-10-17T18:26:35Z</creation-date>
    </product>
    <source>
      <more-information>https://graphical.weather.gov/xml/</more-information>
      <production-center>Meteorological Development Laboratory<sub-center>Product Generation Branch</sub-center></production-center>
      <disclaimer>http://www.nws.noaa.gov/disclaimer.html</disclaimer>
      <credit>https://www.weather.gov/</credit>
      <credit-logo>https://www.weather.gov/logorequest</credit-logo>
      <feedback>https://www.weather.gov/contact</feedback>
    </source>
  </head>
  <data>
    <location>
      <location-key>point1</location-key>
      <point latitude="43.37" longitude="-88.65"/>
    </location>
    <location>
      <location-key>point2</location-key>
      <point latitude="41.93" longitude="-88.75"/>
    </location>
    <moreWeatherInformation applicable-location="point1">https://forecast-v3.weather.gov/point/43.37,-88.65</moreWeatherInformation>
    <moreWeatherInformation applicable-location="point2">https://forecast-v3.weather.gov/point/41.93,-88.75</moreWeatherInformation>
    <time-layout time-coordinate="local" summarization="none">
      <layout-key>k-p6h-n4-1</layout-key>
      <start-valid-time>2017-10-17T19:00:00-05:00</start-valid-time>
      <end-valid-time>2017-10-18T01:00:00-05:00</end-valid-time>
      <start-valid-time>2017-10-18T01:00:00-05:00</start-valid-time>
      <end-valid-time>2017-10-18T07:00:00-05:00</end-valid-time>
      <start-valid-time>2017-10-18T07:00:00-05:00</start-valid-time>
      <end-valid-time>2017-10-18T13:00:00-05:00</end-valid-time>
      <start-valid-time>2017-10-18T13:00:00-05:00</start-valid-time>
      <end-valid-time>2017-10-18T19:00:00-05:00</end-valid-time>
    </time-layout>
    <parameters applicable-location="point1">
      <precipitation type="ice" units="inches" time-layout="k-p6h-n4-1">
        <name>Ice Accumulation</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
      <precipitation type="snow" units="inches" time-layout="k-p6h-n4-1">
        <name>Snow Amount</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
    </parameters>
    <parameters applicable-location="point2">
      <precipitation type="ice" units="inches" time-layout="k-p6h-n4-1">
        <name>Ice Accumulation</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
      <precipitation type="snow" units="inches" time-layout="k-p6h-n4-1">
        <name>Snow Amount</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
    </parameters>
  </data>
</dwml>
```

**Comment by airmanopus** [comment]
This is what the REST url looks like for all of the radar sites at once.

https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXMLclient.php?whichClient=NDFDgen&listLatLon=60.79278,-161.8741%2045.45583,-98.41306%2035.14972,-106.8233%2056.85278,-135.5291%2064.51139,-165.2950%2060.72639,-151.3491%2059.46194,-146.3011%2058.67944,-156.6294%2036.98389,-77.00750%2035.23333,-101.7088%2025.61056,-80.41306%2065.03556,-147.4991%2044.90722,-84.71972%2043.82278,-91.19111%2048.19472,-122.4944%2039.49611,-121.6316%2042.19972,-75.98500%2040.49833,-124.2919%2046.77083,-100.7602%2045.85389,-108.6061%2033.17194,-86.76972%2041.95583,-71.13750%2025.91556,-97.41861%2042.94861,-78.73694%2024.59694,-81.70333%2033.94861,-81.11861%2046.03917,-67.80694%2043.49083,-116.2344%2040.92306,-78.00389%2041.41306,-81.86000%2032.65556,-81.04222%2027.78389,-97.51083%2044.51111,-73.16639%2041.15194,-104.8061%2038.50111,-121.6766%2037.76083,-99.96833%2029.27250,-100.2802%2032.28000,-89.98444%2039.94694,-74.41111%2046.83694,-92.20972%2041.73111,-93.72278%2038.82556,-75.44000%2042.69972,-83.47167%2041.61167,-90.58083%2032.53833,-99.25417%2038.81028,-94.26417%2031.89361,-110.6302%2042.58639,-74.06444%2031.46028,-85.45944%2031.87306,-106.6975%2035

This particular ugliness produces an error:
````xml
<error><h2>ERROR</h2><pre>Point with latitude "38.73028" longitude "-27.32167" is not on an NDFD grid</pre></error>

````

**Comment by airmanopus** [comment]
a partial snippet of what we're getting back

```xml
<parameters applicable-location="point155">
      <precipitation type="ice" units="inches" time-layout="k-p6h-n6-5">
        <name>Ice Accumulation</name>
        <value xsi:nil="true"/>
        <value xsi:nil="true"/>
        <value xsi:nil="true"/>
        <value xsi:nil="true"/>
        <value xsi:nil="true"/>
        <value xsi:nil="true"/>
      </precipitation>
      <precipitation type="snow" units="inches" time-layout="k-p6h-n6-5">
        <name>Snow Amount</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
    </parameters>
  </data>
</dwml>

```

**Comment by airmanopus** [comment]
So the sequence looks something like this
- Cron job runs curl and downloads the results of asking NDFD for snow amount and ice accumulation forecasts for all of the radar sites once per hour
- When client asks for a radar image, if that radar site (i.e,  MKX) has an associated forecast that's more than 0 for amount of snow/ice forecast, then we want to display the snow/ice associated colors in the radar image
- *But* (and this is new) *we also want to display the snow/ice colors for the other radars in a state and in adjacent states*. Imagine you're in Milwaukee and there might be snow coming-- even if you know it's not about to snow where you are, you still look at the radar and look at Minnesota and see where the Blizzard of Whatever Year is located because that's what you do when it's winter and you live in the midwest.

**Comment by airmanopus** [comment]
Working on parsing the dwml; this is a sample of what's downloaded (mainly so I have something small to work with rather than the data for all of the sites)
```xml
{"dwml":{"$":{"version":"1.0","xmlns:xsd":"http://www.w3.org/2001/XMLSchema","xmlns:xsi":"http://www.w3.org/2001/XMLSchema-instance","xsi:noNamespaceSchemaLocation":"https://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd"},"head":[{"product":[{"$":{"srsName":"WGS 1984","concise-name":"time-series","operational-mode":"official"},"title":["NOAA's National Weather Service Forecast Data"],"field":["meteorological"],"category":["forecast"],"creation-date":[{"_":"2017-10-18T18:28:47Z","$":{"refresh-frequency":"PT1H"}}]}],"source":[{"more-information":["https://graphical.weather.gov/xml/"],"production-center":[{"_":"Meteorological Development Laboratory","sub-center":["Product Generation Branch"]}],"disclaimer":["http://www.nws.noaa.gov/disclaimer.html"],"credit":["https://www.weather.gov/"],"credit-logo":["https://www.weather.gov/logorequest"],"feedback":["https://www.weather.gov/contact"]}]}],"data":[{"location":[{"location-key":["point1"],"point":[{"$":{"latitude":"60.79","longitude":"-161.87"}}]},{"location-key":["point2"],"point":[{"$":{"latitude":"45.46","longitude":"-98.41"}}]},{"location-key":["point3"],"point":[{"$":{"latitude":"35.15","longitude":"-106.82"}}]},{"location-key":["point4"],"point":[{"$":{"latitude":"56.85","longitude":"-135.53"}}]}],"moreWeatherInformation":[{"_":"https://forecast-v3.weather.gov/point/60.79,-161.87","$":{"applicable-location":"point1"}},{"_":"https://forecast-v3.weather.gov/point/45.46,-98.41","$":{"applicable-location":"point2"}},{"_":"https://forecast-v3.weather.gov/point/35.15,-106.82","$":{"applicable-location":"point3"}},{"_":"https://forecast-v3.weather.gov/point/56.85,-135.53","$":{"applicable-location":"point4"}}],"time-layout":[{"$":{"time-coordinate":"local","summarization":"none"},"layout-key":["k-p6h-n2-1"],"start-valid-time":["2017-10-18T10:00:00-08:00","2017-10-18T16:00:00-08:00"],"end-valid-time":["2017-10-18T16:00:00-08:00","2017-10-18T22:00:00-08:00"]},{"$":{"time-coordinate":"local","summarization":"none"},"layout-key":["k-p6h-n2-2"],"start-valid-time":["2017-10-18T13:00:00-05:00","2017-10-18T19:00:00-05:00"],"end-valid-time":["2017-10-18T19:00:00-05:00","2017-10-19T01:00:00-05:00"]},{"$":{"time-coordinate":"local","summarization":"none"},"layout-key":["k-p6h-n2-3"],"start-valid-time":["2017-10-18T12:00:00-06:00","2017-10-18T18:00:00-06:00"],"end-valid-time":["2017-10-18T18:00:00-06:00","2017-10-19T00:00:00-06:00"]}],"parameters":[{"$":{"applicable-location":"point1"},"precipitation":[{"$":{"type":"snow","units":"inches","time-layout":"k-p6h-n2-1"},"name":["Snow Amount"],"value":["0.00","0.00"]}]},{"$":{"applicable-location":"point2"},"precipitation":[{"$":{"type":"ice","units":"inches","time-layout":"k-p6h-n2-2"},"name":["Ice Accumulation"],"value":["0.00","0.00"]},{"$":{"type":"snow","units":"inches","time-layout":"k-p6h-n2-2"},"name":["Snow Amount"],"value":["0.00","0.00"]}]},{"$":{"applicable-location":"point3"},"precipitation":[{"$":{"type":"ice","units":"inches","time-layout":"k-p6h-n2-3"},"name":["Ice Accumulation"],"value":["0.00","0.00"]},{"$":{"type":"snow","units":"inches","time-layout":"k-p6h-n2-3"},"name":["Snow Amount"],"value":["0.00","0.00"]}]},{"$":{"applicable-location":"point4"},"precipitation":[{"$":{"type":"snow","units":"inches","time-layout":"k-p6h-n2-1"},"name":["Snow Amount"],"value":["0.00","0.00"]}]}]}]}}

```

**Comment by airmanopus** [comment]
This is the basic idea. Now need to send the output from here into something that radarFilterTest.php can consume.
```javascript
for (let value of forecastPoints) {
  var radarSiteId = radarSites[value].siteId;
  for (var i = 0; i < forecast[value].precipitation.values.length; i++) {
    if (forecast[value].precipitation.values[i].value > 0) {
      *console.log("snow or ice");*
    }
  }
}
```

**Comment by airmanopus** [comment]
curl -k 'https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXMLclient.php?whichClient=NDFDgen&listLatLon=60.79278,-161.8741%2045.45583,-98.41306%2039.973,120.94&product=time-series&begin=2017-10-19T02%3A00%3A00&end=2017-10-19T06%3A00%3A00&Unit=e&snow=snow&iceaccum=iceaccum' > ndfd.dwml

```xml
<?xml version="1.0"?>
<dwml version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd">
  <head>
    <product srsName="WGS 1984" concise-name="time-series" operational-mode="official">
      <title>NOAA's National Weather Service Forecast Data</title>
      <field>meteorological</field>
      <category>forecast</category>
      <creation-date refresh-frequency="PT1H">2017-10-19T01:49:31Z</creation-date>
    </product>
    <source>
      <more-information>https://graphical.weather.gov/xml/</more-information>
      <production-center>Meteorological Development Laboratory<sub-center>Product Generation Branch</sub-center></production-center>
      <disclaimer>http://www.nws.noaa.gov/disclaimer.html</disclaimer>
      <credit>https://www.weather.gov/</credit>
      <credit-logo>https://www.weather.gov/logorequest</credit-logo>
      <feedback>https://www.weather.gov/contact</feedback>
    </source>
  </head>
  <data>
    <location>
      <location-key>point1</location-key>
      <point latitude="60.79" longitude="-161.87"/>
    </location>
    <location>
      <location-key>point2</location-key>
      <point latitude="45.46" longitude="-98.41"/>
    </location>
    <location>
      <location-key>point3</location-key>
      <point latitude="39.97" longitude="120.94"/>
    </location>
    <moreWeatherInformation applicable-location="point1">https://forecast-v3.weather.gov/point/60.79,-161.87</moreWeatherInformation>
    <moreWeatherInformation applicable-location="point2">https://forecast-v3.weather.gov/point/45.46,-98.41</moreWeatherInformation>
    <moreWeatherInformation applicable-location="point3">https://forecast-v3.weather.gov/point/39.97,120.94</moreWeatherInformation>
    <time-layout time-coordinate="local" summarization="none">
      <layout-key>k-p6h-n3-1</layout-key>
      <start-valid-time>2017-10-18T16:00:00-08:00</start-valid-time>
      <end-valid-time>2017-10-18T22:00:00-08:00</end-valid-time>
      <start-valid-time>2017-10-18T22:00:00-08:00</start-valid-time>
      <end-valid-time>2017-10-19T04:00:00-08:00</end-valid-time>
      <start-valid-time>2017-10-19T04:00:00-08:00</start-valid-time>
      <end-valid-time>2017-10-19T10:00:00-08:00</end-valid-time>
    </time-layout>
    <time-layout time-coordinate="local" summarization="none">
      <layout-key>k-p6h-n3-2</layout-key>
      <start-valid-time>2017-10-18T19:00:00-05:00</start-valid-time>
      <end-valid-time>2017-10-19T01:00:00-05:00</end-valid-time>
      <start-valid-time>2017-10-19T01:00:00-05:00</start-valid-time>
      <end-valid-time>2017-10-19T07:00:00-05:00</end-valid-time>
      <start-valid-time>2017-10-19T07:00:00-05:00</start-valid-time>
      <end-valid-time>2017-10-19T13:00:00-05:00</end-valid-time>
    </time-layout>
    <parameters applicable-location="point1">
      <precipitation type="snow" units="inches" time-layout="k-p6h-n3-1">
        <name>Snow Amount</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
    </parameters>
    <parameters applicable-location="point2">
      <precipitation type="ice" units="inches" time-layout="k-p6h-n3-2">
        <name>Ice Accumulation</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
      <precipitation type="snow" units="inches" time-layout="k-p6h-n3-2">
        <name>Snow Amount</name>
        <value>0.00</value>
        <value>0.00</value>
        <value>0.00</value>
      </precipitation>
    </parameters>
    <parameters applicable-location="point3"/>
  </data>
</dwml>
```

**Comment by airmanopus** [comment]
Question: when we get something that's not a number for the snow/ice forecast. how to handle it?

Nome, AK (yay!):
AEC
0.39

Ft. Smith, AR (this is the problem)
SRX
undefined

**Comment by airmanopus** [comment]
Sort of makes sense to put this here; it's a graphic that shows the NDFD weather type on a map of the lower 48. It's the same data that we're pulling from NDFD, except that we're only pulling snow and ice. 
http://www.wpc.ncep.noaa.gov/basicwx/92fndfd.gif

**Comment by airmanopus** [comment]
Still need to generate the start and end times for the URL when we request the forecast data

**Comment by airmanopus** [comment]
Works on my machine (tm).
So next time I am at my desk I need to figure out why this.
ndfd_parse.js:652
for (let point of forecastPoints) {
         ^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Note to self: Clue.
node --version
v0.12.0
node --version
v6.11.3

**Comment by airmanopus** [comment]
from http://forecast.weather.gov/product.php?site=MQT&issuedby=MQT&product=AFD&format=CI&version=1&glossary=1 ret. 15:26 Tuesday Oct 23

> As  the system exits eastward _Tuesday night, enough cold air will
> advect in behind the low to switch precip over from rain to snow_ for
> the high terrain of the west and north-central. With deeper-layer
> synoptic moisture exiting to the east, the extent of precipitation
> in the form of snow remains in question. At this time, the best
> chance for a few inches of accumulating snow will be across the
> Huron Mountains. Given ongoing headlines and high impacts from wind,
> have opted to not highlight snow potential outside of the AFD.

> A few _snow/rain showers will continue into Wednesday_ as a secondary
> weak trough crosses the CWA. Brief ridging will then bring dry
> conditions Wednesday afternoon into Thursday morning.

> A clipper system will pivot across the Upper MS Valley into the
> Upper Great Lakes Thursday afternoon through Friday. While model
> guidance differs on the track across Upper Michigan, the air mass
> will be cold enough to support several inches of accumulating _snow
> for at least the interior west Thursday night_. A slight shift north
> or south in the low pressure track will result in considerable
> differences in potential snow, so will continue to follow a middle-
> ground approach to the forecast this far out.
